### PR TITLE
Sample app added for taking pictures and saving in sqlite db

### PR DESCRIPTION
**Pull request by karaxuna**

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
~~I'm testing the app on Samsung Galaxy S II (android 4.1.2) and after I press the `Take photo` button I get:~~

> ~~Uncaught TypeError: Cannot read property 'DestinationType' of undefined:56~~

---

~~Also on iPhone I did not succeed. Pressing the button gives:~~

> ~~TypeError: undefined is not an object (evaluating 'navigator.camera.getPicture')
> takeAndSavePhotoindex.js:43~~

---

One last thing I noticed so far: the reference to `<script type="text/javascript" src="./jxcore.js"></script>` in _index.html_ is not needed, you may check: https://github.com/jxcore/jxcore-cordova/issues/88#issuecomment-151444752

**Comment by ktrzeciaknubisa** [comment]
Ok, I didn't have `cordova-plugin-camera` installed (because I did not use gulp tasks to set up the app). 
Let's mention plugin requirement in the readme too.

**Comment by ktrzeciaknubisa** [comment]
So It seems to work on iOS too, however there (and also on android), after the photo is taken and we're coming back to the app, the photo is displayed as 1 pixel height bar:

img_0008

**Comment by karaxuna** [comment]
@ktrzeciaknubisa thanks for testing. I have made some changes and there is no more problems about photo height on my android device.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa is it necessary to mention camera plugin? because `gulp build` installs it automatically.

**Comment by ktrzeciaknubisa** [comment]
@karaxuna If someone has already existing cordova app, he/she might use [jxc](https://www.npmjs.com/package/jxc) like I did (e.g. `jxc sample /path/to/photos_sqlite_sample`) or copy _www_ folder manually. IMHO a note like "if you copy a sample manually install the camera plugin" etc. would be useful.

**Comment by ktrzeciaknubisa** [comment]
The photo display is better now :) Not a big deal, however when I did a portrait photo, it displays horizontally:

screenshot_2015-11-30-22-25-44

**Comment by karaxuna** [comment]
@ktrzeciaknubisa Camera orientation problem shall be fixed now

**Pull request closed without merging**
