### PR TITLE
update jxcore version in install_and_run scripts

### PR DESCRIPTION
**Pull request by cdynak**
it will be good to keep the most recent jxcore-cordova-relese version number in install_and_run scripts and all other places.
maybe it could be done automatically, using "version" attribute from package.json?

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
Thank you. I've merged it although there is already 0.0.8 version :)

Generally your idea is right, but the use case for those two scripts was meant to just download one of them (instead of entire repo) and the script will do the rest. Relying on `package.json` etc. would force you to download `package.json` as well.

**Comment by cdynak** [comment]
thank you for merging. :)
i've seen that there is 0.0.8 cordova release, but package.json, plugin.xml, io.jxcore.node.jxp and Changelog.md were updated according to 0.0.7: https://github.com/jxcore/jxcore-cordova/commit/0afb5c26d34509a1ff843939287a91ede1887c36
also version ?*8 (i don't get the version numbering) hasn't been announced at jxcore.com

i think, that downloading `package.json` is good idea, but of course not manually. rather the script itself should get it, parse version number, store in local variable and then use.

**Comment by ktrzeciaknubisa** [comment]
Well, I was working on easier jxcore-cordova deployment for myself and there is already a working dev version of an installer, see https://github.com/jxcore/jxcore-cordova/issues/77.

**Comment by cdynak** [comment]
i've already try it and it works very well. possibly it could replace platform specific scripts and become official tool under any less confusing name (like jxcordova). i'll attach my issues to your jxc repository. thanks very much!

**Comment by ktrzeciaknubisa** [comment]
Thank you!

The `jxc` name was supposed to be short, but your proposal is good as well.

It's still under development, so you may encounter an error or two ;)

**Pull request merged**
