### PR TITLE
Error first style fixed

### PR DESCRIPTION
**Pull request by karaxuna**

### CODE REVIEW

**Comment by ktrzeciaknubisa** [comment]
For testing I edited `sample/www` this way:

``` js
jxcore.isReady(function(err, ret){
    log('isReady  err = ' + err + ', ret =' + ret);
   ...    
}
```

and I get the first arg (`err`) true, while the app seems to work anyway. 

I did the same for `loadMainFile` and `jxcore('asyncPing').call` and they work ok (`err` is  null).

**Comment by karaxuna** [comment]
@ktrzeciaknubisa  are you testing on IOS?

**Comment by ktrzeciaknubisa** [comment]
Oh, yeah. Forgot to mention this.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa I have not fixed it for IOS, asked @obastemur to do it. It shall work for android only yet.

**Comment by ktrzeciaknubisa** [comment]
Right. Ok, for android `err` is proper (null), however `ret` in `jxcore.isReady` is `undefined`. I don't know whether we want to keep `ret` argument here as well? If yes, I believe [this line](https://github.com/jxcore/jxcore-cordova/pull/114/files#diff-1867a750342a71cd98749eda51c038f8L84) should be:

``` js
     callback(null, ret);
```

**Comment by ktrzeciaknubisa** [comment]
IMHO there is no need to keep both args (`err` and `ret`) for `jxcore.isReady`. But then we should not pass an array in [jxcore.java](https://github.com/jxcore/jxcore-cordova/pull/114/files#diff-cbc1b2fa4be9526dd480f395879765dbR302). Instead could be just one `err` having a value `handler == null`

**Comment by ktrzeciaknubisa** [comment]
On the other hand the same applies to `loadMainFile`: `ret` is either `true` or `false` which can be easily checked by `if (!err)` or `if (err)` respectively, thus is redundant.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa agree about that. Will make changes in PR

**Comment by karaxuna** [comment]
@ktrzeciaknubisa sorry, I agree about loadMainFile, because it either loads or error happens. But when isReady callback is called, ret means whether it is ready or not, for example, when isReady is false, we call it again in several milliseconds, but if error happens for some reason, than we should not call it again. Error happens if `errorHandler` is called in callNative function.

**Comment by ktrzeciaknubisa** [comment]
Good point. So since we use `ret` rather internally, then maybe I give up on the idea to pass it to the client by changing into `callback(null, ret);`, what do you think? Then `loadMainFile` can be altered to return just `err`?

**Comment by karaxuna** [comment]
@ktrzeciaknubisa client gets `isReady` response only when either error happens or `ret` is true, so client side can only check `err`, there is not need to send ret (we only need `ret` on server, internally to call isReady again). Sorry if I misunderstood you. 

About loadMainFile, you are right, we can even remove `result` variable at all from `internal_methods['loadMainFile']`.

**Comment by ktrzeciaknubisa** [comment]
> @ktrzeciaknubisa client gets isReady response only when either error happens or ret is true, so client side can only check err, there is not need to send ret (we only need ret on server, internally to call isReady again). Sorry if I misunderstood you. 

Yeap, that's exactly what I meant :)

> About loadMainFile, you are right, we can even remove result variable at all from internal_methods['loadMainFile'].

I agree.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa great, thank you

**Pull request closed without merging**
