### PR TITLE
jxcore-cordova tests

### PR DESCRIPTION
**Pull request by ktrzeciaknubisa**
This is adapted [jxcore-cordova-tests](https://github.com/deefactorial/jxcore-cordova-tests) from @deefactorial heavy work.

Please note, that I removed the _test/LICENSE_ file assuming, that this all will fall under the main LICENSE. Let me know guys if you have any objections.

There are also special notes in README.md for iOS 9, since the original project would not work there due to [security change](https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33):

> Starting in iOS 9.0 and OS X v10.11, App Transport Security (ATS) is enabled as a system default behavior. It improves the privacy and data integrity of connections between an app and web services by using the Transport Layer Security (TLS) protocol version 1.2 (RFC 5246). ATS converts all HTTP requests to HTTPS (RFC 2818) automatically; **attempts to connect insecurely over the Internet fail.**

---

Once this PR will be merged, I'm going to pack it into 0.0.8 release binaries.

### CODE REVIEW

**Comment by obastemur** [comment]
@deefactorial correct me if I'm wrong. Since this is a test related license, we can locate it to a sub folder that it belongs ?

**Comment by ktrzeciaknubisa** [comment]
I'm merging with original license file under _test_ folder.

**Comment by deefactorial** [comment]
Please don't include the stash folder, it isn't necessary for the tests, I only keep it there for reference to the testing I did. The license can be moved.

**Comment by deefactorial** [comment]
I'm fine with you removing the license, it was adapted from the original superagent license, credit may need to be attributed to their project for their tests.

**Pull request merged**
